Traceback (most recent call last):
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/site-packages/nbclient/client.py", line 526, in async_execute
    await self.async_execute_cell(
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/brad/miniconda3/envs/pycourse/lib/python3.8/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib.ticker import MultipleLocator, FixedLocator, FixedFormatter

fig, ax = plt.subplots(figsize=(8,8))
ax.plot(x, f(x))

ax.xaxis.set_minor_locator((0.5))# minor ticks are multiples of 0.5 on X-axis

ax.yaxis.set_major_locator(FixedLocator((0,0.5,1))) # set major tick labels manually
ax.yaxis.set_major_formatter(FixedFormatter(('0', r'$\dfrac{1}{2}$', '1'))) # manual labels - you can use latex
ax.yaxis.set_minor_locator(FixedLocator((1/3, 2/3)))

plt.show(fig)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-8-13ea6ad91021>[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mx[0m[0;34m,[0m [0mf[0m[0;34m([0m[0mx[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m
[0;32m----> 6[0;31m [0max[0m[0;34m.[0m[0mxaxis[0m[0;34m.[0m[0mset_minor_locator[0m[0;34m([0m[0;34m([0m[0;36m0.5[0m[0;34m)[0m[0;34m)[0m[0;31m# minor ticks are multiples of 0.5 on X-axis[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0;34m[0m[0m
[1;32m      8[0m [0max[0m[0;34m.[0m[0myaxis[0m[0;34m.[0m[0mset_major_locator[0m[0;34m([0m[0mFixedLocator[0m[0;34m([0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m0.5[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m [0;31m# set major tick labels manually[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/pycourse/lib/python3.8/site-packages/matplotlib/axis.py[0m in [0;36mset_minor_locator[0;34m(self, locator)[0m
[1;32m   1670[0m         [0mlocator[0m [0;34m:[0m[0;31m [0m[0;31m`[0m[0;34m~[0m[0mmatplotlib[0m[0;34m.[0m[0mticker[0m[0;34m.[0m[0mLocator[0m[0;31m`[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1671[0m         """
[0;32m-> 1672[0;31m         [0mcbook[0m[0;34m.[0m[0m_check_isinstance[0m[0;34m([0m[0mmticker[0m[0;34m.[0m[0mLocator[0m[0;34m,[0m [0mlocator[0m[0;34m=[0m[0mlocator[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1673[0m         [0mself[0m[0;34m.[0m[0misDefault_minloc[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1674[0m         [0mself[0m[0;34m.[0m[0mminor[0m[0;34m.[0m[0mlocator[0m [0;34m=[0m [0mlocator[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/pycourse/lib/python3.8/site-packages/matplotlib/cbook/__init__.py[0m in [0;36m_check_isinstance[0;34m(_types, **kwargs)[0m
[1;32m   2121[0m     [0;32mfor[0m [0mk[0m[0;34m,[0m [0mv[0m [0;32min[0m [0mkwargs[0m[0;34m.[0m[0mitems[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2122[0m         [0;32mif[0m [0;32mnot[0m [0misinstance[0m[0;34m([0m[0mv[0m[0;34m,[0m [0mtypes[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2123[0;31m             raise TypeError(
[0m[1;32m   2124[0m                 "{!r} must be an instance of {}, not a {}".format(
[1;32m   2125[0m                     [0mk[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'locator' must be an instance of matplotlib.ticker.Locator, not a float
TypeError: 'locator' must be an instance of matplotlib.ticker.Locator, not a float

